<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SIGN UP_main-overlay buying</name>
   <tag></tag>
   <elementGuidId>a0ce0cba-f0c5-42be-a789-a7e214614530</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.main-overlay.buying</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2421926b-b585-4362-846d-6e80c13c69b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-overlay buying</value>
      <webElementGuid>24fe57a8-842e-4b69-8585-43807e9cad26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.0.0.3</value>
      <webElementGuid>9d794ef8-8423-40c9-bb29-d718d2f3d398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;main-content buying&quot;]/div[@class=&quot;main-overlay buying&quot;]</value>
      <webElementGuid>aab664e5-919b-40fa-bdf0-b836194728d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div[3]</value>
      <webElementGuid>56a6f1ec-3f09-485f-b7ee-bfa278866162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>3c6c085d-f66b-4c25-8de9-ab17037154df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
