<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Midtrans PillowRp 20,000Get cozy with o_4052a0</name>
   <tag></tag>
   <elementGuidId>80601da7-78e2-47fe-aa44-2c2620fe9e68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ss-box-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>80da1337-fa14-4510-9bec-136a53813ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-box-inner</value>
      <webElementGuid>6ee45248-1f21-4525-ab6e-c822b68b43a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.0.0.2.0.0</value>
      <webElementGuid>a03db89d-2ea8-4fad-9667-7ab8e3e36a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Midtrans PillowRp 20,000Get cozy with our new pillow!Disclaimer: This is not a real transaction.No funds will be transfered out of your account. You should sleep with a proper pillow to refrain yourself from injury.BUY NOWReady to integrate SNAP?SIGN UP  →</value>
      <webElementGuid>fbab886d-8c67-4f74-957d-af0fdd08c286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;ss-box-wrapper&quot;]/div[@class=&quot;ss-box&quot;]/div[@class=&quot;ss-box-inner&quot;]</value>
      <webElementGuid>cbe95508-9ecc-4b63-88ee-84715c3aa369</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div[2]/div/div</value>
      <webElementGuid>4d215d63-a456-4644-80cf-7ab895de18f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coco'])[1]/following::div[14]</value>
      <webElementGuid>0a8e89e4-06ea-43a3-b57f-feb65dca600b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div</value>
      <webElementGuid>310adc0e-5015-410b-aceb-a1c01d7c3b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Midtrans PillowRp 20,000Get cozy with our new pillow!Disclaimer: This is not a real transaction.No funds will be transfered out of your account. You should sleep with a proper pillow to refrain yourself from injury.BUY NOWReady to integrate SNAP?SIGN UP  →' or . = 'Midtrans PillowRp 20,000Get cozy with our new pillow!Disclaimer: This is not a real transaction.No funds will be transfered out of your account. You should sleep with a proper pillow to refrain yourself from injury.BUY NOWReady to integrate SNAP?SIGN UP  →')]</value>
      <webElementGuid>bf15b141-45e7-42d8-9659-a5e60f3d726f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
