<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SIGN UP_main-overlay buying</name>
   <tag></tag>
   <elementGuidId>4ebd8fcf-ba6e-4973-bf69-60b4db063a95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.main-overlay.buying</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2178d0ce-aafd-4b5c-8f43-8eb1facf689e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-overlay buying</value>
      <webElementGuid>bb874991-1528-4fb5-9053-483524061ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.0.0.3</value>
      <webElementGuid>95b0d9b3-6770-4d3c-8ce8-385a192058d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;main-content buying&quot;]/div[@class=&quot;main-overlay buying&quot;]</value>
      <webElementGuid>6b655a47-be2e-4e3b-90df-9cadd4bfb329</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div[3]</value>
      <webElementGuid>a327b2d4-21a8-491a-b545-cf0530b9e63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>53c4efaa-16b2-4b6a-b188-825a568d9b44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
