<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_phone</name>
   <tag></tag>
   <elementGuidId>25a21b92-3c56-489a-b1ff-d4886d6f12d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div[2]/div/div[4]/table/tbody/tr[3]/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98fc799f-ec71-4876-964d-4a175e6b5fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e4090f2c-8379-43cf-b51d-e83a958e9f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>budi@utomo.com</value>
      <webElementGuid>bfe39c3b-dd4a-4643-a0c3-d85828d5144e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.0.1.0.3.0.0.1.1.0</value>
      <webElementGuid>ae15cfad-5aa1-4d22-9a26-0f52b07b4c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;cart-content buying&quot;]/div[@class=&quot;cart-inner&quot;]/div[@class=&quot;cart-section&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[@class=&quot;table-content&quot;]/td[@class=&quot;input&quot;]/input[1]</value>
      <webElementGuid>ff902f90-7c6a-4081-bda7-abfbc937a15c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>dbd52334-09ce-4a9c-a8c4-25647cd6cebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div[2]/div/div[4]/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>1e80a12e-7227-412e-8e57-dfc04308b023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>a161efa0-b794-4e4a-80fa-8a69e7aefa69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>f05d6488-d195-4e9c-9747-83efcc460d5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
