<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_GoPayQRIS</name>
   <tag></tag>
   <elementGuidId>f7c83c16-2720-4e19-aa68-92f1fe3f1eb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.list</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='application']/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>69603097-19dc-44e0-ba8d-9c4d3618c8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>5c8ca668-3a3a-4426-bdbc-6f52880a12af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>list-item</value>
      <webElementGuid>1973614e-aa32-4470-b899-aff8fad47b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/gopay-qris</value>
      <webElementGuid>5fe98391-c3c6-41fd-9d74-6cd420ea27f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GoPay/QRIS</value>
      <webElementGuid>237cd801-5d19-4e19-afe7-6d8b0db8491b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application&quot;)/div[@class=&quot;page-container scroll&quot;]/div[2]/a[@class=&quot;list&quot;]</value>
      <webElementGuid>2323beda-1df3-42b4-9c40-d14ee2597be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackToMerchant/iframe_Save settings_popup_1679041758593</value>
      <webElementGuid>2cf16081-63bb-406e-b2dd-497de9699002</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application']/div/div[2]/a</value>
      <webElementGuid>509a08dc-39a4-4f2e-8444-473970f9303c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select method'])[1]/following::a[1]</value>
      <webElementGuid>ad17205e-3f41-48d6-aac3-4e409ba14652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank transfer'])[1]/preceding::a[1]</value>
      <webElementGuid>077d1f53-5e3c-4837-8f62-939dbf1bfa0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/gopay-qris')]</value>
      <webElementGuid>92727fde-9d41-4434-908a-35d11bead2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>d7107c1e-11cc-4028-b69b-1cd48228c9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/gopay-qris' and (text() = 'GoPay/QRIS' or . = 'GoPay/QRIS')]</value>
      <webElementGuid>ff41e2a4-8eb9-4c5e-b361-933641e777b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
