<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Midtrans PillowRp 20,000Get cozy with o_4052a0</name>
   <tag></tag>
   <elementGuidId>b27d6295-6957-4787-851e-c50a86c69d93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ss-box-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c3b07a01-1894-448d-9a2d-027cdfe8d6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-box-inner</value>
      <webElementGuid>d5f55ded-31cf-4ac9-b93c-0c4db0401145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.0.0.2.0.0</value>
      <webElementGuid>6a03155d-c83a-4b12-a41d-642951a5f0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Midtrans PillowRp 20,000Get cozy with our new pillow!Disclaimer: This is not a real transaction.No funds will be transfered out of your account. You should sleep with a proper pillow to refrain yourself from injury.BUY NOWReady to integrate SNAP?SIGN UP  →</value>
      <webElementGuid>10ca506f-4d6d-45d2-8f5c-b75675599299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;ss-box-wrapper&quot;]/div[@class=&quot;ss-box&quot;]/div[@class=&quot;ss-box-inner&quot;]</value>
      <webElementGuid>e043464d-2b22-4d72-92b3-597b0e976059</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div[2]/div/div</value>
      <webElementGuid>f13025b5-a890-4392-bc42-76e96e362397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coco'])[1]/following::div[14]</value>
      <webElementGuid>bc30e2f2-7f21-4e50-a055-3d4deb9c629a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div</value>
      <webElementGuid>7426322f-32d8-4915-8f18-e32da42c4b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Midtrans PillowRp 20,000Get cozy with our new pillow!Disclaimer: This is not a real transaction.No funds will be transfered out of your account. You should sleep with a proper pillow to refrain yourself from injury.BUY NOWReady to integrate SNAP?SIGN UP  →' or . = 'Midtrans PillowRp 20,000Get cozy with our new pillow!Disclaimer: This is not a real transaction.No funds will be transfered out of your account. You should sleep with a proper pillow to refrain yourself from injury.BUY NOWReady to integrate SNAP?SIGN UP  →')]</value>
      <webElementGuid>4eae0dfa-62ff-4b47-87b2-73f901a157f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
