<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Coco_slide-image</name>
   <tag></tag>
   <elementGuidId>5fa3b529-7073-40ee-b535-af317d47609d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.item.active > div.slide-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='carousel']/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6d5ac25f-3bc6-45e0-99bb-a73198d48900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slide-image</value>
      <webElementGuid>ac536688-b1d6-4d46-ae10-f7e39265e777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.0.0.1.0.$2.0</value>
      <webElementGuid>99a28725-b006-42e9-804b-8c96e7842ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carousel&quot;)/div[@class=&quot;carousel-inner&quot;]/div[@class=&quot;item active&quot;]/div[@class=&quot;slide-image&quot;]</value>
      <webElementGuid>6f46f36d-f2db-44f4-985d-9d00ec4f709c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='carousel']/div/div[3]/div</value>
      <webElementGuid>9f4935a9-2117-4813-bdde-b7dee3fa0cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>27232176-0bd3-4d03-981e-b9ec4a4e4359</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
