<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_DEMO STORE_logo</name>
   <tag></tag>
   <elementGuidId>ae910b3b-7af6-4459-8927-e493de5038d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='header']/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bd7af8cc-7fac-4201-b2e4-fdb06e025965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>5f2d4b2a-cb32-46e8-b238-1bb5f331b21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d2f3dnusg0rbp7.cloudfront.net/snap/assets/close-button-ae5078c33cdb801c630ab3c2d0926d3456b949b0f39a2ad192743131227e6d41.svg</value>
      <webElementGuid>0e397d06-f0b7-4e5d-98e0-f7d63479f4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>3fc26d22-be2e-4c2c-bafd-b0e2604dc737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;title-bar&quot;]/div[@class=&quot;close-snap-button clickable&quot;]/img[@class=&quot;logo&quot;]</value>
      <webElementGuid>92993662-37b1-45ad-820c-f5b880cfa2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NegAmountHuge/iframe_concat(id(, , snap-midtrans, , ))_po_e539dc</value>
      <webElementGuid>8b35838a-bf42-4a1a-a0a7-fdf34ba612ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='header']/div/div[2]/img</value>
      <webElementGuid>aa8188ff-31fe-4c03-a9f5-0d0d78de058b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='close']</value>
      <webElementGuid>60a0ba9e-cc38-4a5e-bbcf-8696732a4db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>8efa7570-6651-4e4f-9c81-543737f3a942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d2f3dnusg0rbp7.cloudfront.net/snap/assets/close-button-ae5078c33cdb801c630ab3c2d0926d3456b949b0f39a2ad192743131227e6d41.svg' and @alt = 'close']</value>
      <webElementGuid>cf6170e2-25b3-4e93-9f17-8ad274811878</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
