<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rp999</name>
   <tag></tag>
   <elementGuidId>3ec6e96d-a719-46fc-8a2d-52af6ab3920f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.header-amount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='application']/div/div/div/div/div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fac17113-392b-44a0-bd2c-66ccd44c4ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-amount</value>
      <webElementGuid>a305f476-3073-4170-abd6-9a5e8146c9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp999</value>
      <webElementGuid>ba77dbda-75e3-4892-99cc-cb7cd7851e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application&quot;)/div[@class=&quot;order-modal&quot;]/div[@class=&quot;order-modal-dialog bottom-padding&quot;]/div[@class=&quot;order-modal-content&quot;]/div[@class=&quot;order-modal-body&quot;]/div[1]/div[@class=&quot;order-summary-section&quot;]/div[@class=&quot;header-amount&quot;]</value>
      <webElementGuid>81886c22-95fe-4351-a5b8-21d7beca75ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AmountCheckout/iframe_concat(id(, , snap-midtrans, , ))_po_51b3df</value>
      <webElementGuid>a31a31ca-b2fc-4222-8674-794384cb0320</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application']/div/div/div/div/div/div/div[3]</value>
      <webElementGuid>6637a2c7-7b9d-4c98-8c1a-c65c9382100c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::div[3]</value>
      <webElementGuid>23943cf1-9797-47a1-8e9b-785285ac8e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your order'])[1]/preceding::div[4]</value>
      <webElementGuid>cabad78d-4d9f-461b-a41e-782366e44932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rp999']/parent::*</value>
      <webElementGuid>704d6a06-d194-4e0d-9acc-ba3759a1918b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]</value>
      <webElementGuid>2f5d59f0-f1c1-4e29-99b9-d9e51578c802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Rp999' or . = 'Rp999')]</value>
      <webElementGuid>52f8717b-5cf5-4809-845a-95954fd6c55d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
