<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Rp999_logo</name>
   <tag></tag>
   <elementGuidId>15580140-b3e7-47b6-bf78-856003092cfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='header']/div[2]/div/div/div[4]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>05319f43-c916-41e5-a423-3f4899ffacb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>7f3e0c84-6269-4f5c-b6e4-a091d9c7fb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d2f3dnusg0rbp7.cloudfront.net/snap/assets/expand_more-a0bd897d2dca356b6989d610317edbf6913f9cf15007ac247344caadcc9a0a44.svg</value>
      <webElementGuid>8a0be401-9eea-41ed-a450-baeb636c4366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>expand</value>
      <webElementGuid>4d367eea-2b7d-4490-9702-90c65d0024c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20px</value>
      <webElementGuid>88e43d7c-de8b-4e69-80e9-ec1bebed1253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20px</value>
      <webElementGuid>db43e8cf-201d-4744-8960-9c181bf162df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;order-header&quot;]/div[@class=&quot;order-box&quot;]/div[@class=&quot;order-summary-section&quot;]/div[4]/div[1]/img[@class=&quot;logo&quot;]</value>
      <webElementGuid>04ccd683-c659-4336-9b24-f8bc2455fbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AmountCheckout/iframe_concat(id(, , snap-midtrans, , ))_po_51b3df</value>
      <webElementGuid>925ae8ac-2910-471f-98d0-4dd182989d3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='header']/div[2]/div/div/div[4]/div/img</value>
      <webElementGuid>df9bb2b4-5101-4acd-9c08-7a3b7f2343d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='expand']</value>
      <webElementGuid>96bae1b9-efc6-43b9-88d2-829278026696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/img</value>
      <webElementGuid>6761cdcb-2626-44c2-b6f1-aa8ed11f6759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d2f3dnusg0rbp7.cloudfront.net/snap/assets/expand_more-a0bd897d2dca356b6989d610317edbf6913f9cf15007ac247344caadcc9a0a44.svg' and @alt = 'expand']</value>
      <webElementGuid>a734b57b-e76c-4975-87f0-c1e9cf3c8856</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
