<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Rp999</name>
   <tag></tag>
   <elementGuidId>746cf406-b1a4-409f-a157-15022cb78581</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.order-summary-content.float-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='application']/div/div/div/div/div[2]/div[2]/table/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>fbda0416-f8c8-4036-9b22-b87a5ea24cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>order-summary-content float-right</value>
      <webElementGuid>a4537920-c482-402f-98b6-078d215ec5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp999</value>
      <webElementGuid>2c0daa54-7fec-4063-8bb2-4eb4250738ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application&quot;)/div[@class=&quot;order-modal&quot;]/div[@class=&quot;order-modal-dialog bottom-padding&quot;]/div[@class=&quot;order-modal-content&quot;]/div[@class=&quot;order-modal-body&quot;]/div[@class=&quot;content-table scroll-y order-modal-wrapper&quot;]/div[@class=&quot;order-summary-subsection&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[1]/td[@class=&quot;order-summary-content float-right&quot;]</value>
      <webElementGuid>01426cf2-7ef7-4f1d-8c3e-18f1c5198c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AmountCheckout/iframe_concat(id(, , snap-midtrans, , ))_po_51b3df</value>
      <webElementGuid>825022c3-3d45-479c-aa80-6c32c978e6de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='application']/div/div/div/div/div[2]/div[2]/table/tbody/tr/td[2]</value>
      <webElementGuid>dcc4f4e7-2278-4b2f-86d4-11df159f391e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Midtrans Pillow'])[1]/following::td[1]</value>
      <webElementGuid>c120cd07-3907-4967-b869-c15d26bb9680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your order'])[1]/following::td[2]</value>
      <webElementGuid>2842257a-3389-4337-8f96-e611e5ceda57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[2]/preceding::td[1]</value>
      <webElementGuid>de7ba9be-ebdc-46f8-b653-7a10119af304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp999'])[3]/preceding::td[2]</value>
      <webElementGuid>eba0618e-d624-4727-87cd-5ee2f8249d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>de86f8a6-6f0a-4709-a695-c0d3f76eb237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Rp999' or . = 'Rp999')]</value>
      <webElementGuid>1d650bd6-d1e1-4ac7-a50e-54e55be08413</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
