<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TEST_modal-iframe</name>
   <tag></tag>
   <elementGuidId>7658886d-3b0c-4dfa-b195-4f98e9240327</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='snap-body']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>69518738-722d-4b1a-abc1-04380db3e120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-iframe</value>
      <webElementGuid>b41e3116-7349-4965-905a-c8859501355c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;snap-body&quot;)/div[@class=&quot;modal-iframe&quot;]</value>
      <webElementGuid>0b95e7dd-a12e-4930-aec7-c7c21c4344a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PopupCheckout/iframe_concat(id(, , snap-midtrans, , ))_po_9b18a6</value>
      <webElementGuid>44cb9630-af65-4b88-9571-4d2a981f9fbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='snap-body']/div</value>
      <webElementGuid>fdbcf433-7429-4440-ba5f-1f4f23c5d827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>3d9fbc8d-c18c-4289-83af-bb0ebea2c761</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
