<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Rp20.000_logo</name>
   <tag></tag>
   <elementGuidId>1065bb1b-bf58-436b-b61b-0c94c09a755d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='header']/div[2]/div/div/div[4]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7fc06d38-324f-4e02-a773-0db6fb571f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>179772fb-e3a6-4e59-921f-93df096f011e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d2f3dnusg0rbp7.cloudfront.net/snap/assets/expand_more-a0bd897d2dca356b6989d610317edbf6913f9cf15007ac247344caadcc9a0a44.svg</value>
      <webElementGuid>50737fce-00b6-4d87-830f-6c4351313c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>expand</value>
      <webElementGuid>764ccead-fa59-40be-a946-a22ba196c0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20px</value>
      <webElementGuid>fd21c817-092b-48e0-abbd-29bca726722f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20px</value>
      <webElementGuid>f11c2bf1-8cf3-4822-a90a-ffe66b04226a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;order-header&quot;]/div[@class=&quot;order-box&quot;]/div[@class=&quot;order-summary-section&quot;]/div[4]/div[1]/img[@class=&quot;logo&quot;]</value>
      <webElementGuid>e84c5c06-8d6a-416c-ba04-9fd45d4fdee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PopupCheckout/iframe_concat(id(, , snap-midtrans, , ))_po_9b18a6</value>
      <webElementGuid>6873d4ff-d606-4dd3-a6ca-b73671e8eef1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='header']/div[2]/div/div/div[4]/div/img</value>
      <webElementGuid>e376027d-0d97-46df-ac54-122627f8d1e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='expand']</value>
      <webElementGuid>d4f0cf12-a11d-4505-a650-3eba0c52559e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/img</value>
      <webElementGuid>f7fc7a0d-e4f2-4c4b-8703-b7c58f57bc18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d2f3dnusg0rbp7.cloudfront.net/snap/assets/expand_more-a0bd897d2dca356b6989d610317edbf6913f9cf15007ac247344caadcc9a0a44.svg' and @alt = 'expand']</value>
      <webElementGuid>599cb208-d096-4eae-bb39-d67e064c15a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
