<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Midtrans PillowRp 20,000Get cozy with o_4052a0</name>
   <tag></tag>
   <elementGuidId>51cdaef1-f0c8-4ae3-a41f-e7c32fd83eef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ss-box-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>96d5bcd4-2cfc-488a-ba08-265b521ad8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ss-box-inner</value>
      <webElementGuid>0fd9b074-a935-4531-8907-849e7038f9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.0.0.2.0.0</value>
      <webElementGuid>4fa1a899-d025-4389-bf9d-9760a69b7af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Midtrans PillowRp 20,000Get cozy with our new pillow!Disclaimer: This is not a real transaction.No funds will be transfered out of your account. You should sleep with a proper pillow to refrain yourself from injury.BUY NOWReady to integrate SNAP?SIGN UP  →</value>
      <webElementGuid>db978c3f-2ea8-4814-b096-4ee695c4c9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;ss-box-wrapper&quot;]/div[@class=&quot;ss-box&quot;]/div[@class=&quot;ss-box-inner&quot;]</value>
      <webElementGuid>7b0c0be7-a77d-4a7b-a60d-3f2c08f17b07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div[2]/div/div</value>
      <webElementGuid>24c5ea07-761d-4d4a-9f07-cbedd1756221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coco'])[1]/following::div[14]</value>
      <webElementGuid>3fc1acf5-c343-4e5b-abb5-57f936ed26e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div</value>
      <webElementGuid>6be0515e-90d6-4e87-b36f-a2c4fc270f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Midtrans PillowRp 20,000Get cozy with our new pillow!Disclaimer: This is not a real transaction.No funds will be transfered out of your account. You should sleep with a proper pillow to refrain yourself from injury.BUY NOWReady to integrate SNAP?SIGN UP  →' or . = 'Midtrans PillowRp 20,000Get cozy with our new pillow!Disclaimer: This is not a real transaction.No funds will be transfered out of your account. You should sleep with a proper pillow to refrain yourself from injury.BUY NOWReady to integrate SNAP?SIGN UP  →')]</value>
      <webElementGuid>fb319da7-5f01-411d-a926-a12e0eb51805</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
