<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_1_text-right</name>
   <tag></tag>
   <elementGuidId>7348df1c-6a4b-4a95-ae11-dd7144742550</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.text-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='20000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8210c2e-a5fc-4b09-9024-b74ce829bdfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-right</value>
      <webElementGuid>c23af116-c6cd-4891-8bce-31349c5515af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>3eee4e02-0fb8-4527-b7f0-866d8226d984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>20000</value>
      <webElementGuid>a0049b8c-f3e3-47dd-920c-82e9bf2efa68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>.0.0.1.0.1.0.1.0:$1.2.0</value>
      <webElementGuid>d2ea9c2e-e87d-4e29-8141-7467c16604b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;cart-content buying&quot;]/div[@class=&quot;cart-inner&quot;]/div[@class=&quot;cart-section&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[@class=&quot;table-content&quot;]/td[@class=&quot;input text-right&quot;]/input[@class=&quot;text-right&quot;]</value>
      <webElementGuid>6cc01238-e158-4b3a-949d-410a0f7ac314</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='20000']</value>
      <webElementGuid>f56954bc-3f0a-443f-9ad4-50097b084674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div[2]/div/div[2]/table/tbody/tr/td[3]/input</value>
      <webElementGuid>b07db299-c8e6-45f7-a919-7e525d37d2ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>40b4e224-c3d3-4f82-872c-b3d3578eac82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number']</value>
      <webElementGuid>ca1a44e9-c07a-4035-803d-ee3f936b960e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
